[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements_numerical.txt"]

[start]
cmd = "python3 -m uvicorn AutoInsight_numerical:app --host 0.0.0.0 --port $PORT"
