[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements_categorical.txt"]

[start]
cmd = "uvicorn AutoInsight_categorical:app --host 0.0.0.0 --port $PORT"
